version: "3"

services:
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config:/etc/prometheus
  grafana-server:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
  loki-server:
    image: grafana/loki
    ports:
      - 3100:3100

